# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: apps/main/.next

jobs:
# Please do not rename this job
  build-project:
    name: build voidtalk
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          CI: true
          NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbmVudG5qY2JpdGJmaXdseXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDkwNjMsImV4cCI6MjA3NDI4NTA2M30.0k_dKzZ8mbLvTlfBCaVuVT72O1LIW1XFbiqO75h7X2w
          NEXT_PUBLIC_SUPABASE_URL: https://xanentnjcbitbfiwlyyg.supabase.co
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm install --global pnpm
          pnpm install
          pnpm build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 400dc899-6d83-410e-bb0f-14d9c5a978a1
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/voidtalk/config.yaml
          action: upload
